# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a set of commands using the runners shell
      - name: Build
        run: |
          sudo apt install g++ make libncurses-dev unzip bc bzip2 libelf-dev libssl-dev git wget cpio -y
          cd
          git clone https://git.buildroot.net/buildroot
          cp .config buildroot
          cd buildroot
          make -j $(nproc)

      - name: Download
        uses: actions/download-artifact@v4.1.8
        with:
          path: ~/buildroot/output/images
